name: Release

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check "Lint and Build" status
        id: check_status
        uses: actions/github-script@v7
        with:
          script: |
            const workflowRuns = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "lint_build.yml",
              branch: "main",
              status: "completed",
              per_page: 1
            });
            const latestRun = workflowRuns.data.workflow_runs[0];
            console.log(`latest lint and build workflow status: ${latestRun.conclusion}`)
            if (latestRun && latestRun.conclusion === "success") {
              core.setOutput('success', 'true');
            } else {
              core.setOutput('success', 'false');
            }

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
        if: steps.check_status.outputs.success == 'true'

      - name: Install dependencies
        run: yarn
        if: steps.check_status.outputs.success == 'true'

      - name: Run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn release
        if: steps.check_status.outputs.success == 'true'